name: Continuous Integration

on:
  push:
    branches:
      - master
      - feature/*
     
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: execute tests
        run: |
          npm install
          npm run test
